### ISSUE TITLE
Group dependencies into one place

### ISSUE THREAD

**Issue by Baklap4** [performous/performous-docker#11]
Currently we have 7 dockerfiles with all containing the aptitude packages or rpm packages.

This list is currently copied over 4 times for ubuntu and 3 times for fedora.

Enhancement would be: Create a way to maintain packages into 1 place instead of the 7 listed places right now.

Solution might be to:
1. Remove all the different version docker files
2. Create one unified ubuntu docker file and one unified fedora dockerfile
3. Accept a [build-arg](https://docs.docker.com/engine/reference/builder/#arg) for the OS version we want to use
4. Change `Build and Push <OS> <VERSION> Container` steps to supply the build-arg
    -  `build-push-action@v2` accepts a `build-arg` input parameter
5. Use non-versioned packages for gcc/clang so we get the latest for the specific platform else we need to if-statement these packages for each os version (can also be done)
6. Optional Profit: if you also add the OS itself to the matrix since all ubuntu's use apt. All fedora's use dnf, all arch uses xxx, all gentoo uses xxx. This way we'll have just 1 dockerfile per packagemanager instead of 1 dockerfile per OS-group

### Dockerfile example

```
## Use the official Ubuntu 18.04 Image from Dockerhub
ARG OS_VERSION
FROM docker.io/library/ubuntu:$OS_VERSION

## Removed other commands from this dockerfile.
```

### GH-actions example
```
ubuntu_18-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Ubuntu 18.04 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        env:
          OS_VERSION: 18.04
        with:
          context: ./
          file: ./Dockerfile.ubuntu
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu$OS_VERSION
          build-arg: $OS_VERSION

      - name: Build and Push Ubuntu 18.04 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        env:
          OS_VERSION: 18.04
        with:
          context: ./
          file: ./Dockerfile.ubuntu
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu$OS_VERSION
          build-arg: $OS_VERSION
```
